
name: pipeline

on:
  push:
    branches:
    - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      myoutput: ${{ steps.step1.outputs.myoutput }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: set output
      id: step1
      run: |
        echo 'detecting changes...'
        echo ''
        API_CHANGED_FILES=( $(git diff --name-only HEAD HEAD^ | grep 'api/*') )
        echo ${#API_CHANGED_FILES[@]} API files changed:
        
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: retrieve output
      run: |
        echo ${{ needs.job1.outputs.myoutput }}
