
name: pipeline

on:
  push:
    branches:
    - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      myoutput: ${{ steps.step_three.outputs.myoutput }}
    steps:
    - name: Set the value
      id: step_one
      shell: pwsh
      run: |
        echo "action_state=yellow" >> $env:GITHUB_ENV
    - name: Use the value
      id: step_two
      shell: pwsh
      run: |
        echo "${{ env.action_state }}"
    - name: set output
      id: step_three
      shell: pwsh
      run: |
        echo "myoutput='${{ env.action_state }}'" >> $env:GITHUB_OUTPUT
        
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: retrieve output
      run: |
        echo ${{ needs.job1.outputs.myoutput }}
